### PR TITLE
Support CTAPHID transport

### PR DESCRIPTION
**Pull request by szszszsz**
Support CTAPHID transport. This is realized by sending CCID traffic into CTAP vendor command. See more details at:
- https://github.com/Nitrokey/oath-authenticator/compare/main...Nitrokey:oath-authenticator:ctaphid#diff-aae62e41d96972219f59df8f75b4937597aeee266ff9f64003f8f4b11b3e78bd

### CODE REVIEW

**Comment by szszszsz** [comment]
@sosthene-nitrokey Bump. Anything to add here?

**Comment by szszszsz** [comment]
One thing this patch would use is to make better error reporting, instead of a single error

**Comment by sosthene-nitrokey** [comment]
Maybe the status bytes could simply be appended to the response like they are normally rather than dropping them?

**Comment by szszszsz** [comment]
> Maybe the status bytes could simply be appended to the response like they are normally rather than dropping them?

So instead of reporting a CTAP error on a failure, always return success and append status bytes? Indeed it seems that there is no other way to move multiple error codes over that channel. And it does not make sense to add own CTAP errors here either. Let's do that.

**Pull request merged**
